class Textos {
  //Quiz
  static const String instrucao1 =
      "Olá, Este é o jogo 'Conhecendo o Tocantins'.";
  static const String instrucao2 =
      "Será feito algumas perguntas sobre recursos naturais, recursos econômicos, questões culturais e sobre a hidrografia do Tocantins, selecione a alternativa que achar correta.";
  static const String instrucao3 =
      "Antes de começar, qual nível de dificuldade você vai jogar? Facil (5 perguntas), Médio (10 perguntas), Difícil (20 perguntas).";
  //Memória
  static const String textoApinaje =
      "O povo Apinajé pertence ao tronco linguístico Macro-Jê. Habita o norte do Estado, em uma área de 141.904 hectares. A terra indígena faz fronteira com os municípios de Tocantinópolis e Maurilândia, Cachoeirinha e Lagoa de São Bento. Sua população atual é de aproximadamente 1.847 pessoas. \n\nOs Apinajé sobrevivem da agricultura de subsistência, da caça e da coleta de babaçu – do qual extraem o óleo das amêndoas e aproveitam a palha para fabricar utensílios domésticos e fazer as coberturas de suas casas. As cascas do babaçu são utilizadas como lenha para cozinhar. Também produzem artesanato de sementes. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoKaraja =
      "Os indígenas Karajá vivem na maior ilha fluvial do mundo, situada entre os rios Tocantins e Araguaia, a Ilha do Bananal. Sua população é de 3.198 pessoas e pertencem ao tronco linguístico Macro-Jê da família Karajá. \nPraticamente vivem do extrativismo, coleta de frutos do cerrado e da pesca. Esse povo destaca-se pela exuberância de seu artesanato, difundidos na arte plumária e pinturas corporais, que representam figuras de animais, pássaros, répteis e peixes, que são apresentadas em suas festas rituais e em nos artefatos cerâmicos. As bonecas Ritxòkò (arte cerâmica) foram tombadas pelo patrimônio histórico e cultural. As bonecas retratam cenas do cotidiano desse povo, como o parto, a morte, a caça e outros espaços e ciclos rituais do povo Karajá. \nNa maioria dos rituais tradicionais, os homens saem para a caça e a pesca, para a recepção dos parentes convidados. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoJavae =
      "Os Javaé se autodenominam Iny, habitam nas barrancas da margem esquerda do rio Javaé, na Ilha do Bananal. Somam uma população de 1.456 pessoas, distribuídas em mais de oito aldeias. O município de sua jurisdição é Formoso do Araguaia, onde esses indígenas fazem seus contatos interculturais com os não indígenas. \nA pesca sempre foi a principal fonte de a base alimentar do povo Javaé, que pescam em lagos e rios no período da seca. Nos períodos chuvosos, alimentam-se da caça e dos produtos agrícolas cultivados no período seco e da aquisição de gêneros alimentícios e outros nas cidades próximas. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoXambioa =
      "Os Karajá do Norte, mais conhecidos como Xambioá, possuem a mesma origem cosmológica do povo Iny, os Javaé e Karajá. Suas terras estão localizadas na região noroeste do Estado e têm uma população de 269 pessoas. \nDevido às situações de contato com a sociedade não indígena, esse povo acabou perdendo seu identificador natural, a língua materna de seus ancestrais e, em decorrência disso, outros aspectos culturais. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoKrahoKanela =
      "Krahô-Kanela, assim foram denominados pelos estudos antropológicos o grupo de pessoas descendente das etnias distintas, o Krahô do Tocantins e o Kanela do Maranhão. O grupo é composto de 84 pessoas. \nO povo Krahô Kanela habita a região centro-oeste do território tocantinense, conhecida como Mata Alagada, próxima ao município de Lagoa da Confusão, terra que, na década de 40, era de seus ancestrais. Atualmente, vive do cultivo de pequenas roças, criação de aves, porcos e de gado. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoKraho =
      "Os indígenas do povo Krahô pertencem ao tronco linguístico Macro-Jê. \nAs terras do povo Krahô são compostas de 302.533 hectares e estão localizadas próximas aos municípios de Itacajá e Goiatins. Sua população é de 2.463 pessoas (FUNASA, 2010). Suas casas são construídas num formato circular entorno de um grande pátio vazio. Esse pátio vazio chamado de (Ka) é um espaço de convivência onde são realizadas discussões da comunidade indígena relacionadas às atividades que serão desenvolvidas. No Ka também acontece uma das tradicionais festas do povo indígena Krahô, a corrida de tora de buriti. A feira da troca de sementes também se tornou uma tradição realizada todos os anos entre o povo Krahô e outros povos. \nPara a sobrevivência, cultivam roças tradicionais: milho, batatas, feijão e outros. \nAssim como outros povos indígenas, fabricam artesanato de sementes de frutos do Cerrado, artesanatos como pulseiras e colares de miçanga e tiririca e artefatos de palha. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoXerente =
      "Os Xerentes se autodenominam Akwẽ, que significa “indivíduo”, “gente importante”. Vieram, migrando provavelmente do Nordeste para o Norte. As terras indígenas do povo Xerente encontram-se situadas à margem direita do rio Tocantins. Divididas em duas partes: Terra Indígena Funil e Terra Indígena Xerente, fazem fronteira com a cidade de Tocantínia e correspondem a 183.542 hectares de área demarcada. Sua população é de 3017 pessoas (FUNASA, 2010). Pertencentes também ao grupo linguístico Macro-Jê, são falantes da língua Akwẽ. \nPela proximidade de suas terras com as cidades circunvizinhas, esse povo tem um contato intenso com as pessoas destes lugares. Por sua localização, seu território encontra-se atualmente rodeado de projetos de grandes lavouras mecanizadas e outros empreendimentos, como barragens e usinas hidrelétricas, que causaram modificação no cotidiano do povo Xerente, tais como, mudanças nos hábitos alimentares e nas práticas socioculturais. \nBastante hábeis na fabricação de artesanatos com a utilização da palha e fibra do babaçu e capim dourado, produzem desde ornamentos corporais utilizados em suas festas tradicionais, como também materiais a serem comercializados. \n\nFonte: Cleide Araújo Barbosa. \nhttps://central.to.gov.br/download/207595.";
  static const String textoAvaCanoeiro =
      "Até a década de 1960, o grupo era conhecido como “Canoeiro” na literatura, em razão da grande habilidade na utilização de canoas nos primórdios do contato com os colonizadores. \nOs Avá-Canoeiro autodenominam-se Ãwa, palavra que, “como em outras línguas tupi-guarani, significa gente, pessoa, ser humano, homem adulto” (Teófilo da Silva, 2005:14). \n\nFonte: Patrícia de Mendonça Rodrigues. \nhttps://pib.socioambiental.org/pt/Povo:Avá-Canoeiro.";
  static const String monumento1 =
      "Homenagem histórica: O monumento, composto por 18 esculturas de bronze em tamanho real, foi idealizado para homenagear os 17 militares e um civil que se rebelaram contra a República Velha no Forte de Copacabana, no Rio de Janeiro, em 1922. Essa revolta, conhecida como Levante do Forte de Copacabana, foi um dos eventos que culminaram na Revolução de 1930.";
  static const String monumento2 =
      "Obra de arte significativa: O Monumento aos Dezoito do Forte de Copacabana é uma obra de arte do escultor brasileiro Maurício Bentes e do arquiteto Oscar Niemeyer. A escultura retrata os 18 rebeldes com expressões heroicas e poses dinâmicas, transmitindo a bravura e a determinação dos homenageados. A obra está situada na Praça dos Girassóis, um dos principais pontos turísticos de Palmas, e se destaca por sua imponência e beleza estética.";
  static const String monumento3 =
      "Localização inusitada: Apesar de remeter a um fato histórico ocorrido no Rio de Janeiro, o monumento se encontra em Palmas, capital do Tocantins. Essa escolha foi motivada pela comemoração do 13º aniversário do estado em 2001, buscando fortalecer a identidade e a memória histórica do Tocantins.";
  static const String relogio1 =
      "Preciso e Funcional: o Relógio do Sol de Palmas não é apenas uma obra de arte; ele é um instrumento funcional e preciso de medição do tempo. Utilizando a sombra projetada por um gnômon, o relógio solar permite que os visitantes leiam a hora com precisão, aproveitando a posição do sol no céu.";
  static const String relogio2 =
      "Símbolo de Sustentabilidade: ao utilizar a luz do sol para medir o tempo, o Relógio do Sol de Palmas simboliza a sustentabilidade e a harmonia com a natureza. Este monumento reflete a intenção da cidade de integrar práticas ecológicas e sustentáveis em seu desenvolvimento urbano.";
  static const String relogio3 =
      "Atração Turística e Educacional: além de ser uma atração turística popular, o Relógio do Sol serve como uma ferramenta educacional. Escolas e grupos frequentemente visitam o local para aprender sobre a astronomia básica, a história dos métodos de medição do tempo e a importância dos relógios solares nas culturas antigas.";
  static const String memorial1 =
      'Homenagem a Luís Carlos Prestes: o Memorial Coluna Prestes foi inaugurado em 2001 e é dedicado a Luís Carlos Prestes, um importante líder comunista brasileiro. O monumento homenageia a "Coluna Prestes", um movimento de guerrilha que percorreu mais de 25 mil quilômetros pelo interior do Brasil entre 1925 e 1927, lutando contra o governo da época e promovendo reformas políticas e sociais.';
  static const String memorial2 =
      "Projeto de Oscar Niemeyer: o Memorial Coluna Prestes foi projetado pelo renomado arquiteto brasileiro Oscar Niemeyer. Conhecido por seu estilo modernista e suas contribuições icônicas para a arquitetura em Brasília, Niemeyer criou o memorial como uma estrutura elegante e simbólica, que reflete a resistência e a luta pela justiça social.";
  static const String memorial3 =
      "Centro Cultural e Histórico: além de ser um monumento, o Memorial Coluna Prestes funciona como um centro cultural e histórico. Ele abriga exposições permanentes e temporárias sobre a vida de Luís Carlos Prestes, a Coluna Prestes e a história política do Brasil. O espaço também é utilizado para eventos culturais, palestras e atividades educacionais, promovendo o conhecimento e a reflexão sobre a história do país.";
}
